<?php
/**
 * Copyright © Mage4. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */

/** @var Mage4\HoverImage\Block\HoverList $block */
?>
<?php if($block->isEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Mage4_HoverImage/js/hover-list": {
                    "hoverData": <?= /* @noEscape */ $block->getHoverImageList(); ?>
                }
            }
        }
    </script>
<?php endif; ?>